name: Main

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      project1: ${{ steps.changes.outputs.project1 }}
      project2: ${{ steps.changes.outputs.project2 }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            project1:
              - 'project1/**'
            project2:
              - 'project2/**'

  build-project1:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.project1 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Project 1 build!"

  build-project2:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.project2 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Project 2 build!"
